"""pgvector voiceprints: owner + opt-in customers

Reshapes speaker_profiles from one-row-per-store (BYTEA blob) into one row per
enrolled voice (typed vector(192)), so identifying a customer by voice becomes a
real nearest-neighbour query.

Hand-written rather than left as autogenerated, for three reasons:

  1. CREATE EXTENSION vector must run BEFORE any vector(192) column exists.
     Autogenerate has no way to know that.
  2. The primary key moves from store_id to id. Alembic does not detect
     primary key changes, so the autogenerated version silently left
     store_id as the PK -- which would have made a second profile per store
     impossible, defeating the entire point.
  3. Autogenerate emitted `ALTER COLUMN embedding TYPE vector(192)` from bytea.
     There is no cast between those types, so that statement fails. The table
     is empty (voiceprint enrolment is not built yet), so dropping and
     recreating is both correct and honest about what is happening.

Revision ID: 3ab3f683fe23
Revises: bde876a95716
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = '3ab3f683fe23'
down_revision: str | Sequence[str] | None = 'bde876a95716'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Must come first: the column type below does not exist without it.
    # postgres:16-alpine does not ship pgvector, so the server image builds it
    # from source -- see Dockerfile.postgres.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Empty table, no data to preserve. Nothing references speaker_profiles, so
    # no CASCADE is needed and none is used -- a CASCADE here could quietly take
    # something else with it in a future where that changes.
    op.drop_table("speaker_profiles")

    op.create_table(
        "speaker_profiles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        # NULL = the owner of this store. Set = that customer.
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("label", sa.Text(), server_default="owner", nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=192), nullable=False),
        sa.Column("sample_count", sa.Integer(), server_default=sa.text("1"),
                  nullable=False),
        sa.Column("threshold", sa.REAL(), server_default=sa.text("0.70"),
                  nullable=False),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consent_source", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"],
                                ondelete="CASCADE"),
        sa.UniqueConstraint("store_id", "customer_id",
                            name="uq_profile_per_customer"),
        sa.CheckConstraint("label IN ('owner','customer')",
                           name="ck_profile_label"),
        # A customer voiceprint is third-party biometric data: it may only exist
        # with recorded consent. In the database, not in a code path.
        sa.CheckConstraint("customer_id IS NULL OR consent_at IS NOT NULL",
                           name="ck_customer_profile_needs_consent"),
    )

    op.create_index("ix_profiles_store", "speaker_profiles", ["store_id"])
    # Exactly one owner profile per store.
    op.create_index("uq_owner_per_store", "speaker_profiles", ["store_id"],
                    unique=True,
                    postgresql_where=sa.text("customer_id IS NULL"))
    # For when a store holds thousands of profiles. At shop scale the planner
    # will prefer ix_profiles_store + exact distance, which is correct.
    op.create_index("ix_profiles_embedding", "speaker_profiles", ["embedding"],
                    postgresql_using="hnsw",
                    postgresql_ops={"embedding": "vector_cosine_ops"})


def downgrade() -> None:
    op.drop_index("ix_profiles_embedding", table_name="speaker_profiles")
    op.drop_index("uq_owner_per_store", table_name="speaker_profiles")
    op.drop_index("ix_profiles_store", table_name="speaker_profiles")
    op.drop_table("speaker_profiles")

    # Back to the original one-row-per-store BYTEA shape.
    op.create_table(
        "speaker_profiles",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.Text(), server_default="owner", nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=False),
        sa.Column("sample_count", sa.Integer(), server_default=sa.text("1"),
                  nullable=False),
        sa.Column("threshold", sa.REAL(), server_default=sa.text("0.70"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("store_id"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
    )

    # The extension is deliberately NOT dropped. DROP EXTENSION is a footgun in
    # a downgrade: it fails if anything else has started using the type, and
    # leaving it installed costs nothing.
