"""initial schema

Revision ID: bde876a95716
Revises: 
Create Date: 2026-08-22 12:36:24.197607

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bde876a95716'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # HAND-WRITTEN (1/2): must run before any table, because every primary key
    # uses gen_random_uuid() as a server default.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner_name', sa.Text(), nullable=False),
    sa.Column('owner_mobile', sa.Text(), nullable=False),
    sa.Column('owner_language', sa.Text(), server_default='hi-IN', nullable=False),
    sa.Column('currency', sa.Text(), server_default='INR', nullable=False),
    sa.Column('timezone', sa.Text(), server_default='Asia/Kolkata', nullable=False),
    sa.Column('api_token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_mobile')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('mobile', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('notify_email', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(name) <> ''", name='ck_name_nonblank'),
    sa.CheckConstraint("email IS NULL OR email ~ '^[^@[:space:]]+@[^@[:space:]]+\\.[^@[:space:]]+$'", name='ck_email_shape'),
    sa.CheckConstraint("mobile ~ '^\\+[1-9][0-9]{7,14}$'", name='ck_mobile_e164'),
    sa.CheckConstraint('NOT notify_email OR email IS NOT NULL', name='ck_notify_needs_email'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'mobile', name='uq_customer_store_mobile')
    )
    op.create_index('ix_customers_store_name', 'customers', ['store_id', sa.literal_column('lower(name)')], unique=False)
    op.create_table('speaker_profiles',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), server_default='owner', nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('sample_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('threshold', sa.REAL(), server_default=sa.text('0.70'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("mode IN ('agent','bridge')", name='ck_conv_mode'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), server_default='email', nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('email')", name='ck_notif_channel'),
    sa.CheckConstraint("status IN ('queued','sent','failed','skipped_no_email')", name='ck_notif_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_queued', 'notifications', ['created_at'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_table('pending_actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spoken_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='awaiting', nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('awaiting','confirmed','cancelled','expired')", name='ck_pending_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pending_awaiting', 'pending_actions', ['store_id'], unique=False, postgresql_where=sa.text("status = 'awaiting'"))
    op.create_table('voice_utterances',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('speaker_role', sa.Text(), nullable=False),
    sa.Column('speaker_score', sa.REAL(), nullable=True),
    sa.Column('audio_uri', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('detected_language', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_confidence', sa.REAL(), nullable=True),
    sa.Column('stt_provider', sa.Text(), server_default='sarvam', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("speaker_role IN ('owner','customer','unknown')", name='ck_speaker_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('api_role', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text_original', sa.Text(), nullable=True),
    sa.Column('lang_original', sa.Text(), nullable=True),
    sa.Column('text_translated', sa.Text(), nullable=True),
    sa.Column('lang_translated', sa.Text(), nullable=True),
    sa.Column('utterance_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("api_role IS NULL OR api_role IN ('system','user','assistant','tool')", name='ck_msg_api_role'),
    sa.CheckConstraint("role IN ('owner','customer','agent','tool')", name='ck_msg_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utterance_id'], ['voice_utterances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'seq', name='uq_message_conv_seq')
    )
    op.create_table('sales',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('utterance_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_mode <> 'khata' OR customer_id IS NOT NULL", name='ck_khata_needs_customer'),
    sa.CheckConstraint("payment_mode IN ('cash','upi','card','khata')", name='ck_payment_mode'),
    sa.CheckConstraint('total >= 0', name='ck_sale_total_nonneg'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utterance_id'], ['voice_utterances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'request_id', name='uq_sale_idempotency')
    )
    op.create_index('ix_sales_store_time', 'sales', ['store_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('signed_amount', sa.Numeric(precision=14, scale=2), sa.Computed('amount * direction', persisted=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('utterance_id', sa.UUID(), nullable=True),
    sa.Column('created_via', sa.Text(), nullable=False),
    sa.Column('reverses_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("created_via IN ('voice','text','api')", name='ck_created_via'),
    sa.CheckConstraint("entry_type IN ('credit_given','payment_received','adjustment','reversal')", name='ck_entry_type'),
    sa.CheckConstraint('amount > 0', name='ck_amount_positive'),
    sa.CheckConstraint('direction IN (1, -1)', name='ck_direction'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['reverses_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utterance_id'], ['voice_utterances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'request_id', name='uq_ledger_idempotency')
    )
    op.create_index('ix_ledger_cust_time', 'ledger_entries', ['store_id', 'customer_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=3), server_default=sa.text('1'), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), sa.Computed('qty * unit_price', persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_items_name', 'sale_items', [sa.literal_column('lower(item_name)')], unique=False)
    # ### end Alembic commands ###

    # HAND-WRITTEN (2/2): the khata is append-only, enforced in the database.
    # A correction is a NEW row with reverses_id set -- never an UPDATE. This
    # holds against future refactors, admin scripts and ad-hoc psql sessions,
    # which is why a shop owner can trust the ledger. It also means
    # ledger_entries needs no separate audit table: it IS the audit log.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION ledger_is_append_only() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION
            'ledger_entries is append-only; insert a reversal row instead'
            USING ERRCODE = 'restrict_violation';
        END $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_ledger_append_only
          BEFORE UPDATE OR DELETE ON ledger_entries
          FOR EACH ROW EXECUTE FUNCTION ledger_is_append_only();
        """
    )



def downgrade() -> None:
    """Downgrade schema."""
    # Trigger first: dropping the table would take it along, but the function
    # is schema-level and would be left orphaned.
    op.execute("DROP TRIGGER IF EXISTS trg_ledger_append_only ON ledger_entries")
    op.execute("DROP FUNCTION IF EXISTS ledger_is_append_only()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sale_items_name', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index('ix_ledger_cust_time', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_sales_store_time', table_name='sales')
    op.drop_table('sales')
    op.drop_table('messages')
    op.drop_table('voice_utterances')
    op.drop_index('ix_pending_awaiting', table_name='pending_actions', postgresql_where=sa.text("status = 'awaiting'"))
    op.drop_table('pending_actions')
    op.drop_index('ix_notif_queued', table_name='notifications', postgresql_where=sa.text("status = 'queued'"))
    op.drop_table('notifications')
    op.drop_table('conversations')
    op.drop_table('speaker_profiles')
    op.drop_index('ix_customers_store_name', table_name='customers')
    op.drop_table('customers')
    op.drop_table('stores')
    # ### end Alembic commands ###
